# Book settings
# template from https://github.com/executablebooks/github-action-demo
title: Inteligencia Artificial para las Ciencias e Ingenierías
author: Raúl Ramos / Universidad de Antioquia
logo: content/local/imgs/fudea.jpg

repository:
   url: https://github.com/rramosp/20201.xai4eng
   branch: master

launch_buttons:
  binderhub_url: ""
  colab_url: https://colab.research.google.com

html:
  google_analytics_id: "UA-43235448-2"

execute:
  execute_notebooks         : off

